---
- name: Add Docker GPG key
  become: true
  ansible.builtin.apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    keyring: '{{ docker_keyring_path }}'
    state: present

- name: Check dpkg architecture
  become: false
  ansible.builtin.command: dpkg --print-architecture
  register: dpkg_architecture
  changed_when: false

- name: Add Docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: 'deb [arch={{ dpkg_architecture.stdout }} signed-by={{ docker_keyring_path }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: present

- name: Install Docker
  become: true
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    groups: docker
    append: true
  when: ansible_user != 'root' and docker_add_user_to_group
